version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@shopify/theme-a11y"
    versions:
    - 4.1.0
  - dependency-name: "@shopify/theme-addresses"
    versions:
    - 4.1.0
  - dependency-name: "@shopify/theme-product"
    versions:
    - 4.1.0
  - dependency-name: "@shopify/theme-product-form"
    versions:
    - 4.1.0
  - dependency-name: "@shopify/theme-sections"
    versions:
    - 4.1.0
  - dependency-name: "@shopify/theme-currency"
    versions:
    - 4.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
